name: pre-commit

on:
  pull_request:
  push:
    branches:
      - main
      - master
      - v0.5.0-next

jobs:
  pre-commit:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-python@v7
      - uses: pre-commit/action@v3.0.1
